name: Run Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: gradle:8.0.2

    services:
      selenium:
        image: selenium/standalone-chrome:3.141.59
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show current directory and contents
        run: |
          pwd
          ls -l

      - name: Wait for Selenium to be ready
        run: |
          for i in {1..30}; do
            if curl http://selenium:4444/wd/hub/status | grep -q "ready"; then
              echo "Selenium is ready"
              break
            fi
            echo "Waiting for Selenium..."
            sleep 2
          done

      - name: Run tests
        run: |
          cd tests/
          gradle test
