name: Ejecutar Pruebas Selenium en Runner Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest # Usamos el runner estándar de GitHub Actions

    services: # Aquí definimos los servicios que corren junto a tu job
      selenium:
        image: selenium/standalone-chrome:3.141.59
        ports:
          - 4444:4444
        options: --health-cmd "curl -f http://localhost:4444/wd/hub/status || exit 1" --health-interval 5s --health-retries 10

    steps:
      - name: Checkout del Código
        uses: actions/checkout@v4

      - name: Instalar Java (OpenJDK 8)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Eclipse Temurin es una buena opción para OpenJDK
          java-version: '8'

      - name: Instalar Gradle
        # Esto es un poco más manual que 'setup-gradle' si necesitas una versión específica no soportada
        run: |
          GRADLE_VERSION=7.4
          wget -q https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
          unzip gradle-$GRADLE_VERSION-bin.zip
          rm gradle-$GRADLE_VERSION-bin.zip
          sudo mv gradle-$GRADLE_VERSION /opt/gradle
          sudo ln -s /opt/gradle/bin/gradle /usr/bin/gradle
          echo "GRADLE_HOME=/opt/gradle" >> $GITHUB_ENV
          echo "/opt/gradle/bin" >> $GITHUB_PATH
          gradle -v

      - name: Navegar a la carpeta de pruebas y Ejecutar Pruebas Gradle
        run: |
          cd tests/ # Asumiendo que tus pruebas están en una subcarpeta 'tests'
          gradle test --info
        env:
          SELENIUM_HOST: selenium # Asegúrate de que tus pruebas usen 'selenium' como hostname